language: java
sudo: false

services:
  - redis-server
  - docker
  - mysql
addons:
  hosts:
    - www.excavator.boot
    - www.excavator.com
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
cache:
  directories:
  - $HOME/.m2

jdk:
- oraclejdk8

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - cat "$TRAVIS_BUILD_DIR/_travis/mysql.cnf" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart
  - mysql -u root --password="root" < dockerfiles/travis.sql
  - mysql -u root -proot -e "show databases"
  - mysql -u root -proot -e "use excavator; show tables"
  - mysql -u root -proot -e "use quartz; show tables"

install:
    #- mvn clean install -DskipTests=true -B -V

script:
    #- mvn -pl redisLimit-spring-boot-starter,helper,authorization-spring-boot-starter,cumulative-spring-boot-starter,lock-spring-boot-starter test
- mvn -pl quartz-spring-boot-starter test
- sh ./check_format.sh


after_script:
  - docker ps
  - docker stop zookeeper
  - docker rm -f zookeeper
