language: java
sudo: false

services:
  - redis-server

addons:
  hosts:
    - www.excavator.boot
    - www.excavator.com

cache:
  directories:
  - $HOME/.m2

jdk:
- oraclejdk8

install:
- mvn clean install -DskipTests=true -B -V
- mvn -pl redisLimit-spring-boot-starter test

script:
- sh ./check_format.sh


