language: java
sudo: false

services:
  - redis-server
  - docker
  - mysql
addons:
  hosts:
    - www.excavator.boot
    - www.excavator.com

cache:
  directories:
  - $HOME/.m2

jdk:
- oraclejdk8

before_install:
  - mysql -e 'CREATE DATABASE excavator;'
  - mysql excavator < dockerfiles/bsc.sql
  - mysql excavator < dockerfiles/quartz.sql

install:
- mvn clean install -DskipTests=true -B -V

script:
- mvn -pl redisLimit-spring-boot-starter,helper,authorization-spring-boot-starter,cumulative-spring-boot-starter,lock-spring-boot-starter test
- mvn -pl quartz-spring-boot-starter test
- sh ./check_format.sh


after_script:
  - docker-compose ps
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose ps
