version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    volumes:
      - container-volume:/var/lib/mysql
      - ./quartz.sql:/docker-entrypoint-initdb.d/quartz.sql
      - ./bsc.sql:/docker-entrypoint-initdb.d/bsc.sql
    environment:
      MYSQL_ROOT_PASSWORD: excavator
      MYSQL_DATABASE: excavator
    ports:
      - "3306:3306"

volumes:
  container-volume:
