name: Excavator Boot on Github Actions
on: [push]

jobs:
  build:
    name: compile excavator boot
    runs-on: ubuntu-latest
    steps:
      - name: git pull repo
        uses: actions/checkout@v1
      - name: maven build
        uses: qcastel/github-actions-maven/actions/maven@master
        with:
          maven-args: "clean install"
      - run: pwd
      - run: ls -rlth

