name: Excavator Boot on Github Actions
on: [push]

jobs:
  build:
    name: compile excavator boot
    runs-on: ubuntu-latest
    steps:
      - name: git pull repo
        uses: actions/checkout@v2
        with:
          java-version: 11
      - name: maven build
        run: 
          mvn clean package -DskipTests 

