name: Excavator Boot on Github Actions
on: [push]

jobs:
  build:
    name: compile excavator boot
    runs-on: ubuntu-latest
    steps:
      - name: git pull repo
        uses: actions/checkout@v3
      - name: Set up Jdk 22
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 23
      - name: maven build
        run: 
          mvn clean package -DskipTests 

