name: Excavator Boot on Github Actions
on: [push]

jobs:
  build:
    name: compile excavator boot
    runs-on: ubuntu-latest
    steps:
      - name: git pull repo
        uses: actions/checkout@v2
      - name: Set up Jdk 17-ea
        uses: actions/setup-java@v1
        with:
          java-version: 17-ea
      - name: maven build
        run: 
          mvn clean package -DskipTests 

